### ISSUE TITLE
Determine hot / cold memory access consequences

### ISSUE THREAD

**Issue by raulk** [filecoin-project/fvm-evm#14]
Lifted from README:

> EVM defines the concept of cold and warm memory access, where first access to a given address is considered cold that is more expensive and subsequent reads or writes to that memory address are considered warm and incur lower gas cost. This comes from [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930). Filecoin does not have a notion of warm and cold storage access so this is kind of meaningless to us in general and is only kept there for now to keep EVM gas accounting accurate.

**Comment by Stebalien** [comment]
Also https://eips.ethereum.org/EIPS/eip-2929.

Basically:

1. EIP2929 keeps track of "hot" and "cold" addresses over the course of a transaction. The FVM analog would be to charge _less_ for actors and IPLD blocks accessed somewhere in the current transaction.
2. EIP2930 allows a caller to preload a set of actors/storage-addresses, paying less up-front.

For our purposes, there are three parts to this:

1. The part that can be observed through EVM gas consumption. This is already implemented.
2. Implement an analog of EIP2930 in Filecoin (would require a FIP). This would allow users to declare addresses & CIDs (or some form of selector) they expect to be used.
3. Implement an analog of EIP2929 in Filecoin (would also require a FIP). We'd charge less gas for reading cached IPLD blocks/accounts.

My conclusion is that there's nothing for us to do for M2.1 or M2.2.

**Comment by raulk** [comment]
> The part that can be observed through EVM gas consumption. This is already implemented.

Just to break this down a little more. The EVM implementation in this repo relies on the _platform_ to determine the cost of SSTORE and SLOAD: https://github.com/filecoin-project/fvm-evm/blob/c92c1b00d801692b1b8901dda08e2cacc5f50a6b/shared/src/instructions/storage.rs#L47-L49. We could consider all accesses to be of fixed type (e.g. likely cold), or to implement some heuristic to determine if the key was accessed or not (e.g. if we have loaded the backing IPLD block into our block registry). However, that would simply affect EVM gas accounting which is practically moot given that execution halt is ultimately determined by Filecoin gas and not EVM gas.

**Comment by raulk** [comment]
Actually, forget it. I thought `System` was a trait that represented the environment (and thus it was up to the environment to report if an access was cold or warm). That's not the case. The System is a concrete type and it's already tracking accesses, so we need to do nothing else here.
